[tool.poetry]
name = "bottlenest"
version = "0.0.13"
description = "A small example package"

license = "MIT"

authors = [
    "Giovanne Feitosa Afonso <giovanneafonso@gmail.com>"
]

repository = "https://github.com/giovannefeitosa/bottlenest"
homepage = "https://github.com/giovannefeitosa/bottlenest"

# README file(s) are used as the package description
readme = ["README.md", "LICENSE"]

# Keywords (translated to tags on the package index)
# keywords = ["packaging", "poetry"]
keywords = ["example"]

# Include template files
include = ["templates/**/*"]

[tool.poetry.dependencies]
# Compatible Python versions
python = ">=3.10,<4"
# Standard dependency with semver constraints
# aiohttp = "^3.8.1"
# Dependency with extras
# requests = { version = "^2.28", extras = ["security"] }
# Version-specific dependencies with prereleases allowed
# tomli = { version = "^2.0.1", python = "<3.11", allow-prereleases = true }
# Git dependencies
# cleo = { git = "https://github.com/python-poetry/cleo.git", branch = "master" }
# Optional dependencies (installed by extras)
# pendulum = { version = "^2.1.2", optional = true }
# Flask
flask = { version = "^2.2.3" }
python-dotenv = "^1.0.0"

# Dependency groups are supported for organizing your dependencies
asyncio = "^3.4.3"
inquirer = "^3.1.3"
[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0"

# ...and can be installed only when explicitly requested
eventlet = "^0.33.3"
python-socketio = "^5.8.0"
requests = "^2.28.2"
[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"

# Python-style entrypoints and scripts are easily expressed
[tool.poetry.scripts]
bottlenest = "bottlenest.__main__:main"
example-apisocket = "examples.apisocket.main:main"
example-clitool = "examples.clitool.main:main"
example-envFile = "examples.envFile.main:main"
example-helloworld = "examples.helloworld.main:main"
example-websocketsClient = "examples.websocketsClient.main:main"
example-websocketsServer = "examples.websocketsServer.main:main"