[tool.poetry]
name = "archimedes-config"
version = "0.1.7"
description = ""
authors = ["BigyaPradhan <bigya.pradhan@optimeering.com>"]
packages = [{include = "archimedes_config"}]

[tool.poetry.dependencies]
python = ">=3.7.0,<3.12"
toml = "^0.10.2"
cryptography = "^39.0.1"
azure-keyvault-secrets = {version = "*",optional = true }
azure-identity = {version = "*",optional = true }
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
isort = "*"
black = "^23.1.0"
pylint = "*"
coverage = "^7.2.1"

[tool.poetry.extras]
azure_keyvault=["azure-keyvault-secrets","azure-identity"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
arckeyl = "archimedes_config.arckeyl:cli"
