[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PopularNewsIndonesia"
version = "0.0.2"
authors = [
  { name="Dwiky", email="damaradwiky6@gmail.com" },
]
description = "A simple package to show 5 popular news from detik.com"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta"
]

[project.urls]
"Homepage" = "https://github.com/DwikyDamara/popular-news-indonesia"
"Bug Tracker" = "https://github.com/DwikyDamara/popular-news-indonesia/issues"