[tool.poetry]
name = "praison"
version = "0.1.0"
description = ""
authors = ["MervinPraison"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.2.0"
scriv = "^1.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
