[tool.poetry]
name = "yapona"
version = "0.1.0"
description = "Pomodoro timer"
authors = ["Dima Lipin <dimich3d@ya.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dbus-next = "^0.2.3"
pygobject = "^3.42.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pylint."MESSAGES CONTROL"]
disable ="missing-class-docstring,missing-function-docstring,no-self-argument,too-many-arguments,too-many-locals,too-many-public-methods,too-many-return-statements,too-many-statements,too-many-lines"
