[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "serialized_data_interface"
version = "0.5.0"
description = "Serialized Data Interface for Juju Operators"
authors = [
    "Dominik Fleischmann <dominik.fleischmann@canonical.com>",
    "Kenneth Koski <kenneth.koski@canonical.com>"
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/canonical/serialized-data-interface/"
repository = "https://github.com/canonical/serialized-data-interface/"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License"
]

[tool.poetry.dependencies]
python = "^3.8"

jsonschema = "3.2"
ops = "^2"
pyyaml = "5.4"
requests = "2.25"

[tool.poetry.dev-dependencies]
black = "20.8b1"
flake8 = "^3.8"
flake8-builtins = "^1.5.3"
flake8-copyright = "^0.2.2"
flake8-docstrings = "^1.6.0"
flake8-polyfill = "^1.0.2"
pep8-naming = "^0.12.1"
isort = "^5.9"
mdformat = "^0.7"
mdformat-gfm = "^0.3"
mypy = "0.910"
pytest = "^6.2"
pytest-mock = "^3.6"
types-jsonschema = "^3.2"
types-pyyaml = "^5.4"
types-requests = "^2.25"
ipdb = "^0.13.9"

[tool.isort]
profile = "black"
