[tool.poetry]
name = "ptal-api"
version = "0.11.2.3"
description = "TALISMAN API adapter"
authors = ["Evgeny Bechkalo <bechkalo@ispras.ru>", "Ivan Medvedev <medvedev.iv@ispras.ru>", "Alexey Isakov <isakov@ispras.ru>"]
readme = "README.md"
packages = [{include = "ptal_api"}]

[tool.poetry.dependencies]
python = "^3.8"
sgqlc = "16.0"
python-keycloak = "2.6.0"
graphql-core = "3.2.3"
transliterate = "1.10.2"
marshmallow-dataclass = "8.5.11"
"ruamel.yaml" = "0.17.21"
click = "8.1.3"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
