[tool.poetry]
name = "jwtserver"
version = "0.0.31"
description = "jwt authorization server"
authors = ["darkdealnet <real@darkdeal.net>"]
readme = "README.md"
license = "Apache2"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: Apache Software License",
]
exclude = ["jwtserver/tests"]

[tool.poetry.urls]
"GitHub" = "https://github.com/darkdealnet/jwtserver"

[tool.poetry.dependencies]
python = "^3.8.1"
uvicorn = "^0.21.1"
loguru = "~0.6.0"
fastapi = "~0.94.1"
sqlalchemy = "~2.0.6"
sqlalchemy_utils = "~0.40.0"
asyncpg = "0.27.0"
psycopg2 = "2.9.5"
httpx = "~0.23.3"
phonenumbers = "~8.13.7"
python-jose = { extras = ["cryptography"], version = "^3.3.0" }
passlib = "1.7.4"
starlette = "^0.26.1"
pydantic = {extras = ["email"], version = "^1.10.6"}
setuptools = "~67.6.0"
pytest = "7.2.2"
redis = { extras = ["hiredis"], version = "^4.5.1" }
python-dotenv = "^1.0.0"
python-multipart = "^0.0.6"
emails = "^0.6"
celery = "^5.2.7"
alembic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.1.0"
asgi-lifespan = "^2.0.0"
pytest-asyncio = "^0.20.3"
pytest = "^7.2.2"
mypy = "^1.1.1"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
updatehead = 'jwtserver.commands:db_upgrade_cmd'
