[tool.poetry]
name = "continual"
version = "v2.0.0a51"
description = "Lifecyle Management for AI"
authors = ["Continual <support@continual.ai>"]
readme = "README.md"
packages = [
    {include = "continual"}
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
grpcio = ">=1.27.1"
pandas = ">=1.0.1"
pyyaml = ">=5.4"
requests = ">=2.28.1"
halo = ">=0.0.30"
grpcio_status = ">=1.31.0"
grpcio-tools = ">=1.43.0,<=1.48.1"
gitpython = ">=3.1.7"
humanize = ">=2.5.0"
google-cloud-storage = ">=1.33.0"
toml = ">=0.10.2"
protobuf = "3.20.3"
GitPython = ">=3.1.29"
numpy = ">=1.21.6"
scikit_learn = ">=1.1.2"
shortuuid = ">=1.0.9"
omegaconf = ">=2.2.3"
pillow = ">=9.0.1"

[tool.poetry.dev-dependencies]
pytest = ">=5.2"

[build-system]
requires = ["poetry>=0.12"]
