[tool.poetry]
name = "babichjacob-emitter"
version = "0.2.0"
description = "An event emitter"
license = "MIT"
authors = ["J or Jacob Babich <jacobbabichpublic+git@gmail.com>"]
readme = "README.md"
repository = "https://github.com/babichjacob/python-emitter"
packages = [{include = "emitter"}]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"

[tool.poetry.dev-dependencies]
black = { version = "^22.12.0" }
mypy = { version = "^0.991" }
pylint = { version = "^2.15.10", python = ">=3.7.2,<4.0" }

[tool.poetry.group.test.dependencies]
pytest = { version = "^7" }
pytest-asyncio = { version = "^0.20.3" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
