[tool.poetry]
name = "test_automation"
version = "0.1.6.1"
description = "test framework for yogiyo"
authors = ["KimKitaeB <kt.kim@wesang.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
pytest = "^7.2.0"
selenium = "^4.5.0"
appium-python-client = "^2.7.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
