[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "pygame-gui-by-zaskar"
version = "0.0.11"
authors = [
  { name="ZaSKaR", email="mark.turkov@mail.ru" },
]
dependencies = [
	"numba >= 0.50.0",
	"scipy >= 1.10.0"
]
description = "some pygame widgets and 3d graphics"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: User Interfaces  ",
    "Operating System :: OS Independent",
]
[project.urls]
"Homepage" = "https://github.com/MarkT5/PygameGUI"
"Bug Tracker" = "https://github.com/MarkT5/PygameGUI/issues"
