[tool.poetry]
name = "bottlenest"
version = "0.0.6"
description = "A small example package"

license = "MIT"

authors = [
    "Giovanne Feitosa Afonso <giovanneafonso@gmail.com>"
]

repository = "https://github.com/giovannefeitosa/bottlenest"
homepage = "https://github.com/giovannefeitosa/bottlenest"

# README file(s) are used as the package description
readme = ["README.md", "LICENSE"]

# Keywords (translated to tags on the package index)
# keywords = ["packaging", "poetry"]
keywords = ["example"]

[tool.poetry.dependencies]
# Compatible Python versions
python = ">=3.10"
# Standard dependency with semver constraints
# aiohttp = "^3.8.1"
# Dependency with extras
# requests = { version = "^2.28", extras = ["security"] }
# Version-specific dependencies with prereleases allowed
# tomli = { version = "^2.0.1", python = "<3.11", allow-prereleases = true }
# Git dependencies
# cleo = { git = "https://github.com/python-poetry/cleo.git", branch = "master" }
# Optional dependencies (installed by extras)
# pendulum = { version = "^2.1.2", optional = true }
# Flask
flask = { version = "^2.2.3" }

# Dependency groups are supported for organizing your dependencies
[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0"

# ...and can be installed only when explicitly requested
[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
Sphinx = "^5.1.1"

# Python-style entrypoints and scripts are easily expressed
[tool.poetry.scripts]
my-script = "my_package:main"
