[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "java_module_dependencies_viewer"
version = "0.0.2"
authors = [
  { name="MKO575", email="mko575@duck.com" },
]
description = "Tool to create or show a diagram representing the dependencies declared in a set of module-info.java files."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: CEA CNRS Inria Logiciel Libre License, version 2.1 (CeCILL-2.1)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Java Libraries",
    "Topic :: Utilities",
]

[project.urls]
"Homepage" = "https://gitlab.com/mko-utilities/java-module-dependencies-viewer"
"Bug Tracker" = "https://gitlab.com/mko-utilities/java-module-dependencies-viewer/-/issues"
