[tool.poetry]
name = "babichjacob-bounded-channel"
version = "0.3.2"
description = "A Python implementation of tokio::sync::mpsc::channel"
license = "MIT"
authors = ["J or Jacob Babich <jacobbabichpublic+git@gmail.com>"]
readme = "README.md"
repository = "https://github.com/babichjacob/python-bounded-channel"
packages = [{include = "bounded_channel"}]

[tool.poetry.dependencies]
python = ">=3.5,<4.0"
babichjacob-option-and-result = "^0.2.0"

[tool.poetry.dev-dependencies]
black = { version = "^22.12.0", python = ">=3.7,<4.0" }
mypy = { version = "^0.991", python = ">=3.7,<4.0" }
pylint = { version = "^2.15.10", python = ">=3.7.2,<4.0" }

[tool.poetry.group.test.dependencies]
babichjacob-oneshot-channel = "^0.3.0"
pytest = { version = "^7", python = ">=3.7,<4.0" }
pytest-asyncio = { version = "^0.20.3", python = ">=3.7,<4.0" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
